SELECT
	l.TITULO, ex.CODEXEMPLAR
FROM
	LIVRO AS l
	INNER JOIN EXEMPLAR AS ex ON l.CODIGO = ex.CODLIVRO
	INNER JOIN EDITORA AS ed ON ed.CODIGO = l.CODEDIT 
WHERE
	ex.VALORAQUISICAO > (
	SELECT
		AVG( ex.VALORAQUISICAO ) 
	FROM
		LIVRO AS l
		INNER JOIN EXEMPLAR AS ex ON l.CODIGO = ex.CODLIVRO
		INNER JOIN EDITORA AS ed1 ON ed1.CODIGO = l.CODEDIT 
		where ed1.CODIGO = ed.CODIGO
		GROUP BY ed1.CODIGO
		ORDER BY AVG(ed.CODIGO) DESC LIMIT 1
	)
GROUP BY ex.CODEXEMPLAR
