SELECT
	e.NOMEEDIT
FROM
	EDITORA AS e
	INNER JOIN LIVRO AS l ON e.CODIGO = l.CODEDIT 
GROUP BY
	e.CODIGO 
HAVING
	count( l.CODIGO ) > (
	SELECT
		count( l.CODIGO ) 
	FROM
		EDITORA AS e
		INNER JOIN LIVRO AS l ON e.CODIGO = l.CODEDIT 
	WHERE
		e.NOMEEDIT = "CAMPUS" 
	GROUP BY
		e.CODIGO 
	)
