SELECT
	a.nome 
FROM
	ALUNO AS a
	INNER JOIN EMPRESTIMO AS e ON e.CODALUNO = a.CODIGO
	INNER JOIN ITEMEMPREST AS ie ON ie.CODEMPREST = e.CODEMPREST 
GROUP BY
	a.CODIGO 
HAVING
	COUNT( e.CODEMPREST ) > (
	SELECT
		count( ie.CODEMPREST ) 
	FROM
		ITEMEMPREST AS ie
		INNER JOIN EXEMPLAR AS ex ON ex.CODEXEMPLAR = ie.CODEXEMPLAR
		INNER JOIN LIVRO AS l ON l.CODIGO = ex.CODLIVRO
		INNER JOIN AUTORIA AS au ON au.CODLIVRO = l.CODIGO
		INNER JOIN AUTOR AS a ON au.CODAUTOR = a.CODIGO 
	WHERE
		a.NOMEAUT = "JACOBSON" 
	GROUP BY
		l.CODIGO 
	) 
ORDER BY
	COUNT( e.CODEMPREST ) DESC
	