SELECT
	l.TITULO,
	a.NOME 
FROM
	ALUNO AS a
	INNER JOIN EMPRESTIMO AS e ON e.CODALUNO = a.CODIGO
	INNER JOIN ITEMEMPREST AS ie ON ie.CODEMPREST = e.CODEMPREST
	INNER JOIN EXEMPLAR AS ex ON ex.CODEXEMPLAR = ie.CODEXEMPLAR
	INNER JOIN LIVRO AS l ON l.CODIGO = ex.CODLIVRO 
WHERE
	e.`DATA` BETWEEN '2019-03-01' 
	AND '2019-03-31' 
	AND ie.DATADEVOL - e.`DATA` <= 2 
GROUP BY
	l.CODIGO,
	a.CODIGO