SELECT
	l.TITULO, count( ie.CODEMPREST ) QTD_EMPRESTIMOS
FROM
	LIVRO AS l
	INNER JOIN EXEMPLAR AS ex ON ex.CODLIVRO = l.CODIGO
	INNER JOIN ITEMEMPREST AS ie ON ie.CODEXEMPLAR = ex.CODEXEMPLAR
	INNER JOIN EMPRESTIMO AS em ON em.CODEMPREST = ie.CODEMPREST 
WHERE
	YEAR ( em.`DATA` ) = 2019 
GROUP BY
	l.CODIGO 
HAVING
	count( ie.CODEMPREST ) = (
	SELECT
		count( ie.CODEMPREST ) 
	FROM
		LIVRO AS l
		INNER JOIN EXEMPLAR AS ex ON ex.CODLIVRO = l.CODIGO
		INNER JOIN ITEMEMPREST AS ie ON ie.CODEXEMPLAR = ex.CODEXEMPLAR
		INNER JOIN EMPRESTIMO AS em ON em.CODEMPREST = ie.CODEMPREST 
		WHERE 
			YEAR ( em.`DATA` ) = 2019 
	GROUP BY
		l.CODIGO 
	ORDER BY
		count( ie.CODEMPREST ) DESC 
	LIMIT 1 
	)
	