UPDATE LIVRO 
SET CODEDIT = ( SELECT CODIGO FROM EDITORA WHERE NOMEEDIT = "LTC" LIMIT 1 ) 
WHERE
	CODEDIT = ( SELECT CODIGO FROM EDITORA WHERE NOMEEDIT = "MAKRON BOOKS" LIMIT 1 );

/*Query para testar o update*/
SELECT
	* 
FROM
	LIVRO AS l
	INNER JOIN EDITORA AS e ON e.CODIGO = l.CODEDIT